formCadastroVersao = new FormGroup({
    enableBannerReportIncome: new FormControl('', [Validators.required]),
    auditoriaEnabled: new FormControl('', [Validators.required]),
    deleteNotification: new FormControl('', [Validators.required]),
    antiEmulador: new FormControl('', [Validators.required]),
    flutterInfosEnableIos: new FormControl('', [Validators.required]),
    flutterSplashEnableIos: new FormControl('', [Validators.required]),
    billetEnabled: new FormControl('', [Validators.required]),
    enableBlockVirtualCard: new FormControl('', [Validators.required]),
    mandatoryRegistrationEnabled: new FormControl('', [Validators.required]),
    flutterGeralEnableIos: new FormControl('', [Validators.required]),
    flutterBannerIrEnableIos: new FormControl('', [Validators.required]),
    notificationEnabled: new FormControl('', [Validators.required]),
    nationality: new FormControl('', [Validators.required]),
    infoList: new FormControl('', [Validators.required]),
    withdrawalInformation: new FormControl('', [Validators.required]),
    civilGender: new FormControl('', [Validators.required]),
    cardBenefits: new FormControl('', [Validators.required]),
    termsList: new FormControl('', [Validators.required]),
    editProfileEnabled: new FormControl('', [Validators.required]),
    webContacts: new FormControl('', [Validators.required]),
    homeConfiguration: new FormControl('', [Validators.required]),
    physicalcardList: new FormControl('', [Validators.required]),
    productAutocontract: new FormControl('', [Validators.required]),
    webStoresLink: new FormControl('', [Validators.required]),
    linkBenefits: new FormControl('', [Validators.required]),
    phoneMetropolitan: new FormControl('', [Validators.required]),
    accountList: new FormControl('', [Validators.required]),
    helpPhoneNumber: new FormControl('', [Validators.required]),
    buildAvailableMessage: new FormControl('', [Validators.required]),
    amountPage: new FormControl('', [Validators.required]),
    outOfServiceMessage: new FormControl('', [Validators.required]),
    tokenActivateMessage: new FormControl('', [Validators.required]),
    idOrigemEnvio: new FormControl('', [Validators.required]),
    baseUrl: new FormControl('', [Validators.required]),
    appStoreUrl: new FormGroup({
      defaultValue: new FormControl('', [Validators.required]),
      ios: new FormControl('', [Validators.required]),
      android: new FormControl('', [Validators.required]),
    }),
    buildMinimumRequired: new FormGroup({
      defaultValue: new FormControl('', [Validators.required]),
      ios: new FormControl('', [Validators.required]),
      android: new FormControl('', [Validators.required]),
    }),
    homeList: new FormGroup({
      defaultValue: new FormControl('', [Validators.required]),
      web: new FormControl('', [Validators.required]),
      description: new FormControl('', [Validators.required]),
    }),
    myCardList: new FormGroup({
      defaultValue: new FormControl('', [Validators.required]),
      web: new FormControl('', [Validators.required]),
    }),
    outOfService: new FormGroup({
      defaultValue: new FormControl('', [Validators.required]),
      ios: new FormControl('', [Validators.required]),
      android: new FormControl('', [Validators.required]),
    }),
    version: new FormGroup({
      versionNumber: new FormControl('', [Validators.required]),
      updateTime: new FormControl('', [Validators.required]),
      email: new FormControl('', [Validators.required]),
      updateOrigin: new FormControl('', [Validators.required]),
      updateType: new FormControl('', [Validators.required]),
    }),
    condition: new FormGroup({
      defaultValue: new FormControl('', [Validators.required]),
    }),
    nome: new FormControl('', [Validators.required]),
    versao: new FormControl('', [Validators.required]),
  });
